// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct METHOD_TYPE_Agent1_ring10 { };
template<> inline void Agent1::_Execute_Method_<METHOD_TYPE_Agent1_ring10>()
{
	this->Agent1::ring10();
}

struct METHOD_TYPE_Agent1_ring12 { };
template<> inline void Agent1::_Execute_Method_<METHOD_TYPE_Agent1_ring12>()
{
	this->Agent1::ring12();
}

struct METHOD_TYPE_Agent1_ring13 { };
template<> inline void Agent1::_Execute_Method_<METHOD_TYPE_Agent1_ring13>()
{
	this->Agent1::ring13();
}

struct METHOD_TYPE_Agent1_ring14 { };
template<> inline void Agent1::_Execute_Method_<METHOD_TYPE_Agent1_ring14>()
{
	this->Agent1::ring14();
}

struct METHOD_TYPE_Agent1_ring8 { };
template<> inline void Agent1::_Execute_Method_<METHOD_TYPE_Agent1_ring8>()
{
	this->Agent1::ring8();
}

struct METHOD_TYPE_Agent1_ring9 { };
template<> inline void Agent1::_Execute_Method_<METHOD_TYPE_Agent1_ring9>()
{
	this->Agent1::ring9();
}

struct METHOD_TYPE_Agent1_takeoff { };
template<> inline void Agent1::_Execute_Method_<METHOD_TYPE_Agent1_takeoff>()
{
	this->Agent1::takeoff();
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
